log_format: '[%(asctime)s][%(lineno)3d][%(levelname)s] %(message)s'
date_time_format: '%m-%d %H:%M:%S'
log_level: 'DEBUG'

sspanel_url: 'https://xxx'
key: 'asdfasdfasdf'

node_id: 0
api_port: 2333
upload_throughput_period: 60
update_port_period: 60
speedtest: 6
docker: false
